version: "3.8"

services:
  mysql:
   image: mysql:latest
   restart: always
   environment:
    - MYSQL_DATABASE=tododb
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASSWORD=root
   expose:
     - "3306"
   volumes:
    - mysql-data:/var/lib/mysql
  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:mysql://mysql:3306/tododb?allowPublicKeyRetrieval=true&useSSL=false
      -schemas=tododb
      -user=root
      -password=root
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql
  todoapp:
    image: todoapp:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tododb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_SHOW-SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQl=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=false
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql:3306/tododb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_FLYWAY_USER=root
      - SPRING_FLYWAY_PASSWORD=root
      - SPRING.FLYWAY.CREATESCHEMAS=true
      - SPRING.BATCH.JDBC.INITIALIZE-SCHEMA=always
      - SPRING.FLYWAY.OUTOFORDER=true
    ports:
      - "8088:8088"
    depends_on:
      - mysql
volumes:
  mysql-data:
      